spring:
  application:
    name: ShopManagerApplication
  profiles:
    active: dev

server:
  port: 8091

# dubbo config
dubbo:

  ## ApplicationConfig Bean
  application:
    id: ShopManagerlApplication
    name: ShopManagerlApplication
    qos-port: 22232

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20881

  ## RegistryConfig Bean
  registry:
    id: fuyi-zk-registry
    address: zookeeper://127.0.0.1:2181