# server domain
host:
  zkserver: 127.0.0.1
  rdserver: 127.0.0.1
  dbserver: 192.168.11.190
  mqserver: 127.0.0.1

# datasource
spring:
  datasource:
    url: jdbc:mysql://${host.dbserver}:3306/fuyi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456