host:
  zkserver: 127.0.0.1
  rdserver: 127.0.0.1
  dbserver: 120.78.193.62
  mqserver: 127.0.0.1

spring:
  application:
    name: UpmsServiceApplication
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://${host.dbserver}:3306/fuyi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: fuyi
    password: 950613

# dubbo config
dubbo:
  scan:
    basePackages: com.fuyi.upms.rpc.service

  ## ApplicationConfig Bean
  application:
    id: ShopServiceApplication
    name: ShopServiceApplication
    qos-port: 22221

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  ## RegistryConfig Bean
  registry:
    id: fuyi-zk-registry
    address: zookeeper://127.0.0.1:2181
    timeout: 9000



