spring:
  application:
    name: ShopPortalWeb
  profiles:
    active: dev

server:
  port: 8092


# service version declare
service:
  shopItemService:
    version: 1.0.0

# dubbo config
dubbo:
  scan:
      base-packages: com.fuyi.shop.portal.controller

  ## ApplicationConfig Bean
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345


