spring:
  application:
    name: ShopPortalWeb
  profiles:
    active: dev

server:
  port: 8092

# service version declare
service:
  shopItemService:
    version: 1.0.0

# dubbo config
dubbo:

  ## ApplicationConfig Bean
  application:
    id: ShopPortalWeb
    name: ShopPortalWeb

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345

  ## RegistryConfig Bean
  registry:
    id: shop-zk-registry
    address: zookeeper://127.0.0.1:2181



