spring:
  application:
    name: UpmsManagerApplication
  profiles:
    active: dev

server:
  port: 8090

jwt:
  header: Authorization
  tokenHead: "Bearer "
  secret: mySecret
  expiration: 86400 # 单位秒=24小时

# dubbo config
dubbo:

  ## ApplicationConfig Bean
  application:
    id: UpmsManagerApplication
    name: UpmsManagerApplication
    qos-port: 22222

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  ## RegistryConfig Bean
  registry:
    id: fuyi-zk-registry
    address: zookeeper://127.0.0.1:2181
    timeout: 9000