spring:
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths: classpath:application.yaml

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/fuyi/upms/dao/mapper/*.xml

server:
  port: 8090
