spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://192.168.11.190:3306/fuyi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/fuyi/upms/dao/mapper/*.xml

server:
  port: 8090
