spring:
  application:
    name: ShopServiceApplication
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths: classpath:application.yaml
  datasource:
    url: jdbc:mysql://${host.dbserver}:3306/fuyi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: fuyi
    password: 950613


host:
  zkserver: 127.0.0.1
  rdserver: 127.0.0.1
  dbserver: 120.78.193.62
  mqserver: 127.0.0.1

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/fuyi/shop/manager/mapper/*.xml

# dubbo config
dubbo:
  scan:
    basePackages: com.fuyi.shop.rpc.service

  ## ApplicationConfig Bean
  application:
    id: ShopServiceApplication
    name: ShopServiceApplication
    qos-port: 22222

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

  ## RegistryConfig Bean
  registry:
    id: fuyi-zk-registry
    address: zookeeper://127.0.0.1:2181



